-- Seed 50 additional question_catalog rows (UK vehicle-insurance-style
-- yes/no eligibility questions), on top of the existing 4.
-- question_id is SERIAL, so ids are assigned automatically (5-54).

INSERT INTO question_catalog (question_label, default_answer) VALUES
('Have you had any driving convictions in the last 5 years?', 'No'),
('Have you made any insurance claims in the last 3 years?', 'No'),
('Is the vehicle kept at your registered address overnight?', 'Yes'),
('Do you use the vehicle for business purposes?', 'No'),
('Is the vehicle modified from manufacturer specification?', 'No'),
('Do you have a valid MOT certificate?', 'Yes'),
('Is the vehicle fitted with an approved alarm system?', 'Yes'),
('Have you been involved in any accidents in the last 3 years?', 'No'),
('Do you park the vehicle in a garage overnight?', 'No'),
('Is the vehicle used for commuting to work?', 'Yes'),
('Have you held a full driving license for more than 2 years?', 'Yes'),
('Do you have any penalty points on your license?', 'No'),
('Is the vehicle your primary means of transport?', 'Yes'),
('Are there any other named drivers on the policy?', 'No'),
('Do any named drivers have driving convictions?', 'No'),
('Is the vehicle used for towing a trailer or caravan?', 'No'),
('Has the vehicle ever been declared a total loss?', 'No'),
('Is the vehicle imported?', 'No'),
('Do you have a black box or telematics device fitted?', 'No'),
('Is the annual mileage under 10,000 miles?', 'Yes'),
('Do you have a no-claims discount?', 'Yes'),
('Has your no-claims discount been protected?', 'No'),
('Is the vehicle used for deliveries or courier work?', 'No'),
('Do you own the vehicle outright?', 'Yes'),
('Is the vehicle on finance or lease?', 'No'),
('Have you ever had a policy cancelled by an insurer?', 'No'),
('Do you smoke inside the vehicle?', 'No'),
('Is the vehicle used by anyone under 25?', 'No'),
('Do you have any pre-existing medical conditions affecting driving?', 'No'),
('Is the vehicle right-hand drive?', 'Yes'),
('Have you disclosed all previous claims?', 'Yes'),
('Is the vehicle used outside the UK regularly?', 'No'),
('Do you have breakdown cover included?', 'No'),
('Is the vehicle fitted with winter tyres?', 'No'),
('Have you completed an advanced driving course?', 'No'),
('Is the vehicle used for racing or track days?', 'No'),
('Do you have a dash cam fitted?', 'No'),
('Is the vehicle kept on a public road?', 'No'),
('Have you provided an accurate vehicle mileage reading?', 'Yes'),
('Do you have a second vehicle insured with us?', 'No'),
('Is the vehicle registered in your name?', 'Yes'),
('Have you disclosed any health conditions relevant to driving?', 'Yes'),
('Is the vehicle used for ride-sharing services?', 'No'),
('Do you have a valid V5C logbook?', 'Yes'),
('Has the vehicle passed its most recent MOT?', 'Yes'),
('Are you the main policyholder?', 'Yes'),
('Is the vehicle used for airport transfers?', 'No'),
('Do you have any unspent criminal convictions?', 'No'),
('Is the vehicle subject to an outstanding recall?', 'No'),
('Have you read and understood the policy terms?', 'Yes'),
('Is the vehicle used for driving instruction?', 'No');
